services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI

  api:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
      - ./downloads:/app/downloads
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./app:/app/app
      - ./downloads:/app/downloads
    depends_on:
      - rabbitmq