[tool.ruff]
line-length = 88
target-version = "py310"
extend-select = ["I"]  # check import sorting too
ignore = [""]      # ignore long line errors (optional)

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]   # allow assert in tests
